### PR TITLE
fix: Remove duplicate quotation from log prefixes

### PR DESCRIPTION
**Pull request by TorontoMedia**
Closes: #940

### CODE REVIEW

**Comment by erig0** [comment]
Hi, I recall there being issues when `IndividualCalls=yes`. Can you add test coverage for that? iptables for example, will pass the strings via CLI instead of using a temporary file and `iptables-save`. So the quoting can be tricky.

**Comment by TorontoMedia** [comment]
> Hi, I recall there being issues when `IndividualCalls=yes`. Can you add test coverage for that? iptables for example, will pass the strings via CLI instead of using a temporary file and `iptables-save`. So the quoting can be tricky.
> 
> Edit: I just realized this is fixing a particular instance of over quotation. Maybe it's okay after all. Perhaps the quotes are left over from when firewalld used to call the `nft` CLI.

I also believe that it's just leftover from the previous implementation but I've found a few more issues with duplicate quotation and have added the test for `IndividualCalls`. 

At some point we should consolidate the testing of all logging features.

**Comment by erig0** [comment]
> At some point we should consolidate the testing of all logging features.

I've been adding new coverage in `src/tests/features`. But for fix for specific bugs I'm still dropping them in `src/tests/regressions`.

You could also tag the test case `AT_KEYWORDs(log)`. Then `make check TESTSUITEFLAGS="-k log"` will run it.

**Review by erig0 — APPROVED** [review]
This looks good. Thanks! Merging.

**Pull request merged**
