### PR TITLE
Added Steam LAN transfer service

### PR DESCRIPTION
**Pull request by DanMan**
Implements #1163 

https://help.steampowered.com/en/faqs/view/46BD-6BA8-B012-CE43

https://github.com/ValveSoftware/steam-for-linux/issues/9938

### CODE REVIEW

**Review by brinkabeler — APPROVED** [review]
seems legit

**Comment by erig0** [comment]
Hi, the steam support docs [1] say this:

> The network transfer happens on TCP port 27040 and it needs to be allowed by local firewall software. You also need to open UDP ports 27031-27036 for client discovery.

Maybe we also need the UDP ports?

[1]: https://help.steampowered.com/en/faqs/view/46BD-6BA8-B012-CE43

**Comment by erig0** [comment]
Before this can merge we needinfo about the above question.

> Hi, the steam support docs [1](https://help.steampowered.com/en/faqs/view/46BD-6BA8-B012-CE43) say this:
>
> > The network transfer happens on TCP port 27040 and it needs to be allowed by local firewall software. You also need to open UDP ports 27031-27036 for client discovery.
>
> Maybe we also need the UDP ports?

**Comment by koloved** [comment]
> Before this can merge we needinfo about the above question.

i tried download game without the UDP 27031-27036, its not working, then turns its on and its working, tried two times

**Comment by koloved** [comment]
@DanMan can you add that ports please ?

**Comment by DanMan** [comment]
The same UDP port range is already part of the Steam Streaming config. Does it still need to be included here?

**Review by erig0 — APPROVED** [review]

**Pull request merged**
