### PR TITLE
Service XML Schema

### PR DESCRIPTION
**Pull request by traek**
Ensures XML author basic conformity to 'man firewalld.service'

### CODE REVIEW

**Comment by traek** [comment]
Addresses my request for #488

**Comment by erig0** [comment]
@traek, see commit 81d3d6a7d84b and the handful of commits that precede it. A schema previously existed, but was removed in favor of the built in `--check-config` option. What is your use case for XSD that can't be served by `firewall-offline-cmd --check-config` ?

**Comment by charlie1968** [comment]
If you have a bunch of XML config files to edit, I can import the XSD and support in my favorite IDE for writing the xml files would be great.

**Comment by ciez** [comment]
thank you very much for the effort, @traek !

Much appreciated

**Comment by Tristan971** [comment]
Seconding charlie in this case. The builtin CLI checker is great if you need a last syntax+semantics check at the time of deployment of the configuration, but it doesn't entirely overlap with XML schemas.

With those, one's IDE can handle silly typos and syntactically invalid things very early on, and even provide autocomplete suggestions that helps find options one might not have missed while skimming through the documentation, etc.

Overall I don't quite see why it would be one or the other rather than both?

**Comment by thom311** [comment]
I agree that schemas are useful and should be (re) added.

Since schemas exist in the past, I think we should instead revert their removal, and not add a (different) schema from this pull request. Also, this pull-request only covers services, while the revert covers also `check`, `icmptype`, `ipset`, and `zone`, and adds utility script. Also, the `services.xsd` schema from this pull request does not validate the currently existing schemas (which would be fixable).

Instead, I think it's better to close this PR and instead do a revert (pull request 1198).

I am sorry for the long time it took, and then preferring another approach in the end. Thank you for your efforts though!

**Pull request closed without merging**
