### PR TITLE
feat(build): distribute an OCI container image

### PR DESCRIPTION
**Pull request by erig0**
See commit message and README.

### CODE REVIEW

**Comment by erig0** [comment]
@mheon, if you have time can you take a quick look? Is this a sensible way to do this?

**Comment by mheon** [comment]
I wouldn't consider it necessary to dump the image as a tar file - I'd be content to stop at a built image and print the name and SHA of the built image, then let the user proceed from there. Main reasoning that that passing around archives isn't a common way of handling images - IMO, users pushing to a registry they control would be a more typical next step.

Beyond that, it looks fine.

**Comment by erig0** [comment]
> I wouldn't consider it necessary to dump the image as a tar file - I'd be content to stop at a built image and print the name and SHA of the built image, then let the user proceed from there.

I was intending to post the built images alongside the released source tarball, i.e. `make dist`.

> Main reasoning that that passing around archives isn't a common way of handling images - IMO, users pushing to a registry they control would be a more typical next step.

So as part of the firewalld release process, tagging and pushing an image to quay.io or other would be preferable?

**Comment by mheon** [comment]
Ah, sorry for misunderstanding - thought this was mainly intended for development.

Tagging + pushing to a place like `quay.io` is probably a better workflow, yes. Distributing a tarball of the image alongside it (e.g. in the Github release) is not a bad idea, but I'd view that as a backup/archival solution in case the registry has issues or purges older images after a large number of images are hosted.

**Pull request merged**
