### PR TITLE
fix(firewall-config): escape markup stored in bindings store

### PR DESCRIPTION
**Pull request by yrro**
Fixes: #499

### CODE REVIEW

**Review by thom311 — APPROVED** [review]
lgtm, thanks

**Comment by thom311** [comment]
> Are these strings causing an issue? AFAICS, none of these strings need to be escaped. Or do the translated strings need escaped?

the strings come from translation and are not hardcoded to the program itself. They go through a `_()` call.

It would require translators (or the maintainers) to review those strings, and make sure that everything is markup-safe. 
Which is not the case, see #499 or try `G_DEBUG=fatal-warnings LANG=en_GB.UTF8 firewall-config`

**Comment by yrro** [comment]
> Are these strings causing an issue? AFAICS, none of these strings need to be escaped.

Run `firewall-config` with `LANG=en_GB.UTF-8` and you'll see the problem:

image

The tree view on the left is supposed to have a row "Interfaces", but because the cell renderer doesn't like the invalid markup (logging `Failed to set text from markup due to error parsing markup: Unknown tag 'interface' on line 1 char 20`) it doesn't render and instead whenever you move your mouse over the bugged entry the rendered text changes to be a copy of one of the other cells.

**Comment by erig0** [comment]
I follow you now. So this translation is triggering the bug:
https://github.com/firewalld/firewalld/blob/57f584b97ed5878aee9bfddfab04ed2f44c0df52/po/en_GB.po#L147-L148

I suppose we should just escape these given the translation problem.

**Review by erig0 — APPROVED** [review]

**Pull request merged**
