### PR TITLE
Fix Neighbor Discovery when using drop zone

### PR DESCRIPTION
**Pull request by hwoarang**
This adds two commits needed to fix the ND when an interface belongs to the drop zone

- Patch#1 Accepts neighbour-advertisement message to the 'raw' table
- Patch#2 Accepts all needed ND packets in the filter table which is needed if the default policy on the filter table is 'DROP/REJECT' (eg drop zone)

### CODE REVIEW

**Comment by herrold** [comment]
This needs more thought

We have noticed that in a VM environment, and with people using third party IPv6 tunnelling, that they (perhaps unwillingly) also turn on their radvd, and so pollute the local and accurate advertisements from an authoritative radvd

We need to be able to * and under iptables / ebtables DO * filter out such 'rogue' advertisements

**Comment by hwoarang** [comment]
Back you can still add your rules on the `raw_prerouting` chain to actually drop these packets right? Dropping something in any table which drop the packet entirely, whereas accepting it in a table, will still make it traverse the rest of them.

**Comment by erig0** [comment]
@hwoarang, please see PR #380 for an alternative solution.

**Comment by erig0** [comment]
Closed in favor of alternative fix #380.

**Pull request closed without merging**
