### PR TITLE
Fix bad translation for "Interfaces" in several translations

### PR DESCRIPTION
**Pull request by yrro**
Fixes: #499

### CODE REVIEW

**Comment by thom311** [comment]
Sorry for no reply for such a long time...

There are changes like
```diff
 msgid "Interfaces"
-msgstr "<interface>"
+msgstr ""
``` 
which seems not a correct translation update.

I cannot fix this, because I am not (sufficiently) familiar with the languages.


I think this pull request should be closed (or reworked).

**Comment by yrro** [comment]
> There are changes like
> 
> ```diff
>  msgid "Interfaces"
> -msgstr "<interface>"
> +msgstr ""
> ```
> 
> which seems not a correct translation update.
> 
> I cannot fix this, because I am not (sufficiently) familiar with the languages.
> 
> I think this pull request should be closed (or reworked).

I think this is how you indicate that there is no translation, i.e., fall back to `msgid`. This lets translators know that the string needs to be translated.

**Comment by thom311** [comment]
Hi. You are correct. Patch makes sense to me!

The branch should be rebased to latest `master` (I don't have permission to do that). Rebasing will result in conflicts, due to the changes to the "PO-Revision-Date:".

**Comment by yrro** [comment]
Done, thanks

**Comment by yrro** [comment]
Although GitHub shows that latest push as making loads of changes, it's just a rebase onto the latest `main` branch that doesn't change anything.

**Review by erig0 — APPROVED** [review]

**Pull request merged**
