### PR TITLE
improvement(service):  Samba: Use service includes

### PR DESCRIPTION
**Pull request by ykgmfq**

### CODE REVIEW

**Comment by marcosfrm** [comment]
`samba-client.xml` can include `netbios-ns.xml` .

`<helper name="netbios-ns"/>` can then be dropped from `samba.xml`, `samba-client.xml` and `samba-dc.xml`, no? (as far as I know it only works with 137/udp)

**Comment by erig0** [comment]
> `samba-client.xml` can include `netbios-ns.xml` .
> 
> `<helper name="netbios-ns"/>` can then be dropped from `samba.xml`, `samba-client.xml` and `samba-dc.xml`, no? (as far as I know it only works with 137/udp)

It should go further than that. There is a also a `netbios-ns` service.
e.g. `samba-dc` include `samba` which includes `samba-client` which includes `netbios-ns`.

**Review by erig0 — APPROVED** [review]
LGTM. Thanks!

**Comment by erig0** [comment]
Note: CI failure is due to an upstream nftables change in the rule output. I'll address it separately and not block this PR.

**Pull request merged**
