### PR TITLE
Create ts3.xml

### PR DESCRIPTION
**Pull request by Baterka**
Added Teamspeak 3 service

### CODE REVIEW

**Comment by Baterka** [comment]
?

**Comment by Baterka** [comment]
lol

**Comment by erig0** [comment]
I haven't merged this yet because it's missing changes to `config/Makefile.am` and `po/POTFILES.in`. I can do those manually or you can repush with the changes.

**Comment by thom311** [comment]
```
<port protocol="udp" port=" 9987"/>
```

I think the space before the number should be dropped. While the code is relatively forgiving (to be nicer to humans who don't get everything correct), the XML files we ship should be strict.

Also, the 3 patches would need to be squashed into one, and rebased to `master`.


Aside those minor issues, the pull requests looks good to me.

**Pull request closed without merging**
