### PR TITLE
FIX: Module/Helper loading broken in Centos 7.4 for conntrack_proto_g…

### PR DESCRIPTION
**Pull request by kvishnivetsky**
FIX: Module/Helper loading broken in Centos 7.4 for conntrack_proto_gre #263

### CODE REVIEW

**Comment by kvishnivetsky** [comment]
Hi, Eric.
Ok - I agree, that maybe this is some kind of **workaround**, but what if we add a **configureation flag**, that will regulate this behaviour? Kernel fixup is rather long process, and this issue is rather actual - GRE is a popular proto.

**Comment by erig0** [comment]
After speaking with colleagues, I think our best path forward is below.

In get_nf_conntrack_helpers():

- module name matches "nf_conntrack_proto_*"

or

- "-helper" in the "alias:" line of modinfo

Similarly for get_nf_nat_helpers():

- module name matches "nf_nat_proto_*"

or

- "NAT helper" in "description:" line

**Comment by kvishnivetsky** [comment]
Ok. I'll make corrections in patch.

**Comment by erig0** [comment]
Thanks @kvishnivetsky. I took your PR, squashed the commit, and added a couple fixes on top. I hope to push it soon - just waiting on testsuite to finish.

**Pull request closed without merging**
