### PR TITLE
fix: allow use of kernel builtins for nf_conntrack helpers

### PR DESCRIPTION
**Pull request by djlucas**
Tested only on SysV with all modules built in. Works for me. Somebody more competent in Python can probably clean that up a bit. I'm concerned about the duplicate lines, but wasn't sure if 'ret' could be reused in that context, and this _should_ still work for mixed modules and built-ins (though I did not test that). This should tie in with #517 (opened also by me).

HTH

### CODE REVIEW

**Comment by djlucas** [comment]
Oops, forget to remove the extraneous print statements used while testing.

**Comment by djlucas** [comment]
Checking status, for whatever reason, I guess I borked the squash. The commit above (without the green checkmark) is the squashed commit (15bfa3b), and effectively what was tested. If needs be, I'll close, destroy that fork, and resubmit a proper commit, just say so.

Thanks.

**Comment by djlucas** [comment]
Tested with mixed builtins and modules. Checks OK

**Comment by erig0** [comment]
This PR was closed. Instead of the fixes here modinfo usage was completely removed in commit adbf3476b7533ef3a2c002db62f76614a9f0f6c1.

**Pull request closed without merging**
