### PR TITLE
improvement(github): translate templates to yaml

### PR DESCRIPTION
**Pull request by TorontoMedia**
Convert issue templates from markdown to yaml. This will require adopting two labels `bug` and `triage`.

### CODE REVIEW

**Comment by erig0** [comment]
I created the labels. Do you feel we need to automatically tag new issues with "bug"? Maybe we can just use "triage" and only tag as "bug" if someone has confirmed it is: a) still an issue and b) actually a bug.

**Comment by TorontoMedia** [comment]
> I created the labels. Do you feel we need to automatically tag new issues with "bug"? Maybe we can just use "triage" and someone manually tags as "bug" if it is: a) still an issue and b) actually a bug. Rationale is that a lot of reports fall into those two categories.

I agree. To make the templates more ambiguous, I removed the titles and added a config file that allows blank templates.

**Comment by TorontoMedia** [comment]
I also made `What happened` in `bug_report.yml` and `What would you like to be added` in `enhancement.yml` a requirement.

**Review by erig0 — APPROVED** [review]
Thanks @TorontoMedia!

**Comment by erig0** [comment]
> 



> @erig0 Thank you for merging my pull request. In config.yml, I believe we should capitalize the mailing list names to improve the appearance of the template list. Are you open to another pull request that does this?

Sure.

**Pull request merged**
