### PR TITLE
Alternative sysconfig file

### PR DESCRIPTION
**Pull request by hwoarang**
This patchset adds new -f/--system-config-firewall-file options to allow users to set a different file to import firewall configuration from compared to /etc/sysconfig/system-config-firewall

### CODE REVIEW

**Comment by t-woerner** [comment]
Please have a look at these commits:
https://github.com/t-woerner/firewalld/commit/08bdf7fa4a9c6675e1ac860e0b762dea0d3cde1f
https://github.com/t-woerner/firewalld/commit/24c9b20f91bda34517fc9f81affe8f0f467c2fce
These are enhanced versions of the proposed changes.

**Comment by erig0** [comment]
Closing as per t-woerner's comment above. Current code has these implemented.

**Comment by erig0** [comment]
Closing as per t-woerner's comment. This has been implemented in current code.

**Comment by erig0** [comment]
Closing as per t-woerner's comment. This is is implemented in current code.

**Pull request closed without merging**
