### PR TITLE
fix: match daddr to oifname and saddr to iifname

### PR DESCRIPTION
**Pull request by fargburger**
fix: Fixes this issue where ipsets with IPs and interfaces are mismatched between outbound interface and destination IP address

https://github.com/firewalld/firewalld/issues/1399#issuecomment-2420036920

### CODE REVIEW

**Comment by beninidavide** [comment]
I too replicated the same issue; using iptables as backend works correctly, while using nftables I have the issue  

I am testing sending a UDP packet from an external server to my host
(10.100.53.42); on my host the following zone and ipset are defined

zone "test1", in which I add an ipset made of one host.
```bash
# firewall-cmd --zone=test1 --list-all
test1 (active)
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: dhcpv6-client ssh
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
	rule family="ipv4" source ipset="test" log prefix="test1 " level="debug" accept
```
the ipset "test":
```bash
# firewall-cmd --get-entries --ipset=test
10.100.52.226/32,eth0
```


## Using iptables as backend
I can see (output of `iptables-save`)
```bash
[...]
-A IN_test1_allow -p tcp -m tcp --dport 22 -j ACCEPT
-A IN_test1_allow -m set --match-set test src,src -j ACCEPT
-A IN_test1_log -m set --match-set test src,src -j LOG --log-prefix "test1 " --log-level 7
```
When sending a packet from the allowed source 10.100.52.226, the packet is accepted; in firewall logs I see:  
```kernel: [    C0] test1 IN=eth0 OUT= MAC=52:54:ee:d4:ee:b8:52:54:ee:54:ce:7d:08:00 SRC=10.100.52.226 DST=10.100.53.42 LEN=35 TOS=0x00 PREC=0x00 TTL=64 ID=11666 DF PROTO=UDP SPT=48073 DPT=9999 LEN=15```

When sending a packet from another IP, the packet is blocked as expected

## Using nftables as backend
firewall logs show that a packet from 10.100.52.226, which was previously passing when using iptables as backend, is now
rejected:
```kernel: [    C0] filter_IN_test1_REJECT: IN=eth0 OUT= MAC=52:54:ee:d4:ee:b8:52:54:ee:54:ce:7d:08:00 SRC=10.100.52.226 DST=10.100.53.42 LEN=35 TOS=0x00 PREC=0x00 TTL=64 ID=2324 DF PROTO=UDP SPT=59530 DPT=9999 LEN=15```

and the output of nft list says:

```bash
# nft -a list chain inet firewalld filter_IN_test1_allow
table inet firewalld {
	chain filter_IN_test1_allow { # handle 340
		tcp dport 22 accept # handle 344
		ip6 daddr fe80::/64 udp dport 546 accept # handle 345
		ip saddr . oifname @test accept # handle 347
	}
}
```

Now I add a rule using iifname:
```bash
# nft insert rule inet firewalld filter_IN_test1_allow position 347 ip saddr . iifname @test accept
# nft -a list chain inet firewalld filter_IN_test1_allow
table inet firewalld {
	chain filter_IN_test1_allow { # handle 340
		tcp dport 22 accept # handle 344
		ip6 daddr fe80::/64 udp dport 546 accept # handle 345
		ip saddr . iifname @test accept # handle 455
		ip saddr . oifname @test accept # handle 347
	}
}
```

Now I try again sending the udp packet and it's accepted (only from the adddress
10.100.52.226, others are blocked)

**Comment by fargburger** [comment]
@beninidavide  thank you for confirming that, I had a very similar test case.  What I couldn't tell was whether it was programmed this way for a good reason for any other cases.  I couldn't get the unit tests to run on my development machine (I wasn't trying that hard) but if the maintainers need me to improve this PR, I'm more than happy to.  

I thought I fixed the Semantic issues too - but maybe that step doesn't get re-checked in github?

**Comment by erig0** [comment]
This fix looks correct. I'm keeping it open until test coverage can be added. I'll try to get to it next week.

**Review by erig0 — DISMISSED** [review]
I added a test. IMO this is ready to merge after CI.

**Pull request merged**
