### PR TITLE
Added fish shell completions

### PR DESCRIPTION
**Pull request by exploide**
I noticed this repository already contains shell completions for bash and zsh. This PR adds a completion script for fish.

### CODE REVIEW

**Comment by exploide** [comment]
@erig0 do you have any opinion on this?

I would like to have this resolved and it is totally fine if you don't want to include fish completions. I would then just submit them to fish itself.

But since bash and zsh completions are already present, I thought it would be best to contribute fish completions here.

Just let me know.

**Comment by erig0** [comment]
On Wed, Apr 29, 2020 at 09:39:42AM -0700, Jannik Vieten wrote:
> @erig0 do you have any opinion on this?

Shell completions are welcome. I'm just backlogged. Sorry. I'll get to
it eventually.

**Comment by exploide** [comment]
Just rebased this PR on master and updated the completion file with options changed in 0.9.x.

@erig0 anything else missing to get this merged? Otherwise I would submit the completions to fish-shell to get them to the users.

**Comment by exploide** [comment]
I'm closing this PR since the completion file is now shipped with fish itself. No worries. :smiley:

**Comment by erig0** [comment]
Thanks. Sorry for the inactivity.

**Pull request closed without merging**
